### ISSUE TITLE
Error corrected in repo but not in npmjs.com

### ISSUE THREAD

**Issue by frneer** [danofa/solar-orionjs#2]
Hi There danofa, my name is Francisco Rossi, currently im developing some software which includes this module. The problem is there was a bug you corrected some month ago concerning a typo (orionObject/object) in create function. The soft is aimed to run in docker containers so everytime we create a new one after installing all dependencies and modules we have to change this line, is there any posibility that you could update this version to npmjs.com?

The error is in line 114/115 of index.js orionObject or object.

Thanks in advance!

Let me know if I can help you to do this or maybe do this by myself.

Greattings.

Francisco Rossi.

**Comment by danofa** [comment]
Hi Francisco ! Thank you for the issue, I had completely forgot to update npmjs :) its now done.
